name = 'Dumper'

[[images]]
    name = 'redis'
    tags = ['latest','6','6.0','6.2','6.2.6','5','5.0']

[[images]]
    name = 'mysql'
    tags = ['latest','8','8.0','8.0.26','5','5.7','5.7.35','5.6','5.6.51']

[[images]]
    name = 'mongo'
    tags = ['latest','5','5.0','5.0.3']

[[images]]
    name = 'alpine'
    tags = ['latest','3','3.11','3.12','3.13','3.14','3.14.2','3.13','3.13.6']